seed: 12345
project_name : &dataset "ncaltech101"

model: "dagt"

task: "detection"

ema: True
ema_decay: 0.995

dataset: *dataset
data_directory: "../data/"

exp_name: "test"

dataloader:  
  batch_size : &bs 16
  num_workers: 8
  pin_memory: True

model_params:
  backbone:
    in_channels: 24
    num_blocks: 4
    hidden_channels_list: [36, 48, 66, 66, 66]
    last_voxel_div: '5x7'
    # final_size: 16
    pe_dim: 12
    pe_aggr: 'add'
    pool_aggr: 'max'
    keep_temporal_ordering: False
    self_loop: False
    encoding_periods: [1, 1, 1]
    factors: [1,1,1]
    num_heads: 1
    dropout_trans: 0.1
    dropout_ff: 0.1
    norm_func: 'layer'
    num_scales: &ns 1
    args_gr:
      radius: 0.01
      max_neighbors: 16

  head:
    activation: relu
    edge_attr_dim: 2
    aggr: sum
    kernel_size: 5
    pooling_aggr: max
    base_width: 0.5
    after_pool_width: 1
    net_stem_width: 1
    yolo_stem_width: 1
    num_scales: *ns

augmentations:
  aug_trans: 0.1
  aug_p_flip: 0
  aug_zoom: 1

n_nodes: 50000

time_window_us: 1000000

resume: none

# early_stopping:
#   patience: 5
#   min_delta: 1e-3
#   min_epochs: 20
#   metric: "loss"

# criterion:
#   label_smoothing : 0.1

scheduler_type: "cosineTrans"

max_epochs : 100
scheduler_max_epochs: 800
warmup_epochs: 3

optimizer:
  lr : 1e-4
  weight_decay : 0.0

clip: 0.1

scheduler:
  eta_min: 0.0

checkpoint_save:
  best_loss: True
  best_acc: True
  best_loss_ema: True
  best_acc_ema: True

output_directory: "./test_dagt"